// This file is generated by kconfig_compiler_kf5 from audex.kcfg.
// All changes you do to this file will be lost.

#include "preferences.h"

#include <qglobal.h>
#include <QSettings>
#include <QStandardPaths>
#include <QDialog>
#include <QDialogButtonBox>

#include "widgets/devicewidget.h"
#include "widgets/generalsettingswidget.h"
#include "widgets/profilewidget.h"

class PreferencesHelper
{
  public:
    PreferencesHelper() : q(nullptr) {}
    ~PreferencesHelper() { delete q; q = nullptr; }
    PreferencesHelper(const PreferencesHelper&) = delete;
    PreferencesHelper& operator=(const PreferencesHelper&) = delete;
    Preferences *q;
};

Q_GLOBAL_STATIC(PreferencesHelper, s_globalPreferences)

Preferences *Preferences::self()
{
  if (!s_globalPreferences()->q) {
    new Preferences;
    s_globalPreferences()->q->read();
  }

  return s_globalPreferences()->q;
}

Preferences::Preferences(QObject* parent)
  : QObject(parent)
{
  Q_ASSERT(!s_globalPreferences()->q);
  s_globalPreferences()->q = this;
}

Preferences::~Preferences()
{
  // sync settings
  save();

  if (s_globalPreferences.exists() && !s_globalPreferences.isDestroyed()) {
    s_globalPreferences()->q = nullptr;
  }
}

void Preferences::read()
{
  QSettings settings;
  bool firstRun = settings.value("firstRun", QVariant::fromValue(true)).toBool();

  if (firstRun)
    resetDefaults();

  setFirstRun(firstRun);
  setOverwriteExistingFiles(settings.value("overwriteExistingFiles").toBool());
  setDeletePartialFiles(settings.value("deletePartialFiles").toBool());
  setEjectCDTray(settings.value("ejectCDTray").toBool());
  setCddbLookupAuto(settings.value("cddbLookupAuto").toBool());
  setCoverLookupAuto(settings.value("coverLookupAuto").toBool());
  setFetchCount(settings.value("fetchCount").toInt());
  setParanoiaMode(settings.value("paranoiaMode").toBool());
  setNeverSkip(settings.value("neverSkip").toBool());
  setSampleOffset(settings.value("sampleOffset").toInt());
  setBasePath(settings.value("basePath").toString());
  setGuiWidth(settings.value("guiWidth", 800).toInt());
  setGuiHeight(settings.value("guiHeight", 600).toInt());
  setGuiLayout(settings.value("guiLayout", 0).toInt());
  setStylePalette(settings.value("stylePalette").toString());
}

void Preferences::save()
{
  QSettings settings;

  settings.setValue("firstRun", firstRun());
  settings.setValue("overwriteExistingFiles", overwriteExistingFiles());
  settings.setValue("deletePartialFiles", deletePartialFiles());
  settings.setValue("ejectCDTray", ejectCDTray());
  settings.setValue("cddbLookupAuto", cddbLookupAuto());
  settings.setValue("coverLookupAuto", coverLookupAuto());
  settings.setValue("fetchCount", fetchCount());
  settings.setValue("paranoiaMode",paranoiaMode());
  settings.setValue("neverSkip", neverSkip());
  settings.setValue("sampleOffset", sampleOffset());
  settings.setValue("basePath", basePath());
  settings.setValue("guiWidth", guiWidth());
  settings.setValue("guiHeight", guiHeight());
  settings.setValue("guiLayout", guiLayout());
  settings.setValue("stylePalette", stylePalette());
  settings.sync();
}

void Preferences::resetDefaults()
{
  QSettings settings;
  settings.setValue("overwriteExistingFiles", false);
  settings.setValue("deletePartialFiles", true);
  settings.setValue("ejectCDTray", false);
  settings.setValue("cddbLookupAuto", true);
  settings.setValue("coverLookupAuto", true);
  settings.setValue("fetchCount", 8);
  settings.setValue("paranoiaMode", true);
  settings.setValue("neverSkip", true);
  settings.setValue("sampleOffset", 0);
  settings.setValue("basePath", QStandardPaths::writableLocation(QStandardPaths::MusicLocation));
  settings.setValue("guiWidth", 800);
  settings.setValue("guiHeight", 600);
  settings.setValue("guiLayout", 0);
  settings.setValue("guiLayout", 0);
}

void Preferences::showDialog(QWidget* parent, ProfileModel* profileModel)
{
    QDialog dialog(parent);

    QTabWidget* tab = new QTabWidget;

    generalSettingsWidget * page_gen = new generalSettingsWidget();
    page_gen->kcfg_styleDark->setChecked((stylePalette() == "dark"));
    page_gen->kcfg_basePath->setText(basePath());
    page_gen->kcfg_cddbLookupAuto->setChecked(cddbLookupAuto());
    page_gen->kcfg_coverLookupAuto->setChecked(coverLookupAuto());
    page_gen->kcfg_deletePartialFiles->setChecked(deletePartialFiles());
    page_gen->kcfg_ejectCDTray->setChecked(ejectCDTray());
    page_gen->kcfg_fetchCount->setRange(1, 99);
    page_gen->kcfg_fetchCount->setValue(fetchCount());
    page_gen->kcfg_overwriteExistingFiles->setChecked(overwriteExistingFiles());
    tab->addTab(page_gen, tr("General Settings"));

    deviceWidget * page_dev = new deviceWidget();
    page_dev->kcfg_neverSkip->setChecked(neverSkip());
    page_dev->kcfg_paranoiaMode->setChecked(paranoiaMode());
    page_dev->kcfg_sampleOffset->setRange(-10000, +10000);
    page_dev->kcfg_sampleOffset->setValue(sampleOffset());
    tab->addTab(page_dev, tr("Device Settings"));

    profileWidget * page_pro = new profileWidget(profileModel);
    tab->addTab(page_pro, tr("Profiles"));

    // top layout
    QVBoxLayout* topLayout = new QVBoxLayout;

    // add tab
    {
      QHBoxLayout* hLayout = new QHBoxLayout;
      hLayout->addWidget(tab);
      topLayout->addLayout(hLayout, 0);
    }

    // add button box
    QDialogButtonBox * buttonBox = new QDialogButtonBox(QDialogButtonBox::Close);
    buttonBox->setCenterButtons(true);
    connect(buttonBox, SIGNAL(rejected()), &dialog, SLOT(accept()));
    topLayout->addWidget(buttonBox);

    // main grid
    QGridLayout * mainGrid = new QGridLayout;
    mainGrid->addLayout(topLayout, 0, 0);
    dialog.setLayout(mainGrid);

    dialog.exec();

    setStylePalette(page_gen->kcfg_styleDark->isChecked() ? "dark" : "light");
    setBasePath(page_gen->kcfg_basePath->text());
    setCddbLookupAuto(page_gen->kcfg_cddbLookupAuto->isChecked());
    setCoverLookupAuto(page_gen->kcfg_coverLookupAuto->isChecked());
    setDeletePartialFiles(page_gen->kcfg_deletePartialFiles->isChecked());
    setEjectCDTray(page_gen->kcfg_ejectCDTray->isChecked());
    setFetchCount(page_gen->kcfg_fetchCount->value());
    setNeverSkip(page_dev->kcfg_neverSkip->isChecked());
    setOverwriteExistingFiles(page_gen->kcfg_overwriteExistingFiles->isChecked());
    setParanoiaMode(page_dev->kcfg_paranoiaMode->isChecked());
    setSampleOffset(page_dev->kcfg_sampleOffset->value());

    save();
}
